### ISSUE TITLE
Publish as a separate npm package

### ISSUE THREAD

**Issue by alessandro-newzoo** [zackad/prettier-plugin-twig-melody#11]
Hello @zackad,

first of all I wanna **thank you** from the bottom of my heart for creating this fork.
I've been desperately looking for a Twig Prettier plugin that works with Prettier 3 for about a year now, and yours is the very first I came across to that supports it, so infinite kudos for that! ❤️

[I've asked the guys at TailwindCSS to add support for your fork to their Prettier plugin](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/254) `prettier-plugin-tailwindcss`, and they're willing to help as long as you can publish this fork as a separate package:

> Ah they haven't published a separate package and are relying users putting in the GitHub url the dependency version. I think it'd probably best to wait until they publish this as a scoped package with version published to npm. I'll keep an eye on it though to see if that happens.

Is it something you would consider doing?

Thank you very much for your time,
Alessandro

**Comment by zackad** [comment]
Hi @alessandro-newzoo,

thanks for your interest in this project. Publishing as npm package is something I will consider if there's enough interest from other people.

In the meantime I'm still trying to convert this project into ES module (not sure if that a requirement) and have difficulty on setting up automatic testing with `jest`.

**Comment by idflood** [comment]
Hi @zackad ,

Thanks for your awesome work : ) I would be very interested in the seperate package. Also, if this is possible, it could be published in the current state, and the ES module + automated testing with jest can be added in a second step.

For reference here is another discussion with a few people trying to find a way to make prettier work with twig files: https://github.com/tailwindlabs/tailwindcss/discussions/11731

**Comment by zackad** [comment]
Hi @idflood,

I've publish this as `@zackad/prettier-plugin-twig-melody`. Would love some feedback as I'm not really testing it.

**Comment by alessandro-newzoo** [comment]
hey @zackad thank you so much for this!
I've tested it and it seems to install and work fine, well done 🎉

Only some dependencies warnings though I'm not sure how concerning they are

```
npm WARN deprecated shortid@2.2.16: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
```

**Comment by zackad** [comment]
I'll mark this as completed.

Unfortunately to fix those warnings, we need to update project dependencies which is not a straighforward process. I'm not sure how to handle updating `melody-*` packages. Should I fork and publish updated version into separate packages or bring them all into this project.

**Comment by alessandro-newzoo** [comment]
thank you zackad! 🖤
Personally I would either fork or branch out to test it, then merge into this package to keep things more streamlined.
I'm pretty busy at the moment, but I can give it a try some day in the future when I'm free (no promises about a positive outcome though haha).
